apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: customers-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: customers
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70